REBASE 2
rebase idk what number

REBASE

rebase many small things

rebase take 3

rebase again: vim-c mostly

vim-c: add link keys

vim-c and doom

vim-c: overhaul and rebinds

vimium-c: overhaul, t for tabs

vim-c: hovering is actually useful

vim-c: fix tf and TF

vimrc: fix esc/alt

doom: l-tab-tab to alternate tabs

Rebase minor dotfile changes

doom: fix fzf to open in default-dir

vimium-c: yt uses 0, doom: fzf

doom: fix fzf

(fire)libre(fox)wolf extensions

bashrc: rm protection

scrunch vim-c stuff

vim stuff

scripts and stuff

vim-c imagedl|profile remove ln|rewrite lilo

reorganize scripts, remove emoji scripts

vim-c: D for duplicate action

vim-c: command mode

more librewolf remove ext

librewolf: ublock

remove "i don't care about cookies", UB does this

librewolf: add link for ublock

lw: remove decentraleyes

gitignore additions

fix gitignore: git rm r cached

doom remove snippets

doom and ranger

doom: code eval and yasnippet

doom: add personal site project

ranger use bookmarks

doom: don't save snippets

gitignore pls work

doom: custom doesn't need to be synced

doom, vim, remove gitignore

remove git stuff

rebind fzf to "doom-esque"

vim: just use c-a for increment

feh: fix keys

fixing some dotfiles

vim-c: remove google, localfile rules

extract: add tbz

vim-c: add cv to link keys

scripts: use scrot, fix divac

doom: add notes org-publish

vimium-c : more rebinds

vim man

vimrc: keep it simple stupid

i3

xfce: fix bindings, mpv: more sane defaults

feh: rebind c-f c-b

vimrc: c-j, c-k

diff --git a/scripts/lilo b/scripts/lilo
--- a/scripts/lilo
+++ b/scripts/lilo
@@ -1,32 +1,74 @@
 #!/bin/bash
+# lilo: stitch two images side-by-side
 
-# lilo: stitch two images side-by-side and display
+set -e
 
-echo $@
-exit
+RED='\033[1;31m'
+NC='\033[0m'
 
-help() {
-    echo "$(basename $0): provide 2 images to stitch together"
-    echo "Usage: $(basename $0) [RIGHT] [LEFT]"
+usage() {
+    echo
+    echo "Usage: $(basename $0) [OPTIONS] [RIGHT] [LEFT]"
+    echo "Stitch RIGHT and LEFT images, and save as a new image."
+    echo
+    echo "  -h              display this message exit"
+    echo "  -r              reverse order RIGHT and LEFT"
+    echo "  -v              stitch images vertically (default horizontally)"
+    echo "  -o              specify output file"
 }
 
 if [ $# -lt 2 ]; then
-    >&2 echo "ERROR: Please provide two files."
-    echo
-    help
+    >&2 echo -e "${RED}ERROR: Please provide two files.${NC}"
+    usage
     exit 1
 fi
+
+while getopts ":hvro::" o; do
+    case "${o}" in
+        h)
+            usage
+            exit
+            ;;
+        v)
+            vertical=1
+            ;;
+        r)
+            reverse=1
+            ;;
+        o)
+            output=${OPTARG}
+            ;;
+        *)
+            usage
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND-1))
 
 right=$(basename $1)
 left=$(basename $2)
 
-ext="${right##*.}"
+if [ -z $vertical ]; then
+    operation="+append"
+else
+    operation="-append"
+fi
 
-rbase=${right%.$ext}
-lbase=${left%.$ext}
+if [ -z $reverse ]; then
+    temp=$left
+    left=$right
+    right=$temp
+fi
 
+rext="${right##*.}"
+lext="${left##*.}"
+rbase=${right%.$rext}
+lbase=${left%.$lext}
 
-OUTPUT="${rbase}-${lbase}.${ext}"
+if [ -z $output ]; then
+    output="${rbase}-${lbase}.${rext}"
+fi
 
-echo $OUTPUT
-convert $left $right +append $OUTPUT
+convert $left $right $operation $output
+echo $output
