minor changes

diff --git a/scripts/lilo b/scripts/lilo
--- a/scripts/lilo
+++ b/scripts/lilo
@@ -2,9 +2,15 @@
 
 # lilo: stitch two images side-by-side and display
 
+help() {
+    echo "$(basename $0): provide 2 images to stitch together"
+    echo "Usage: $(basename $0) [RIGHT] [LEFT]"
+}
+
 if [ $# -lt 2 ]; then
-    >&2 echo "lilo: provide 2 images to stitch together"
-    >&2 echo "Usage: $(basename $0) RIGHT LEFT"
+    >&2 echo "ERROR: Please provide two files."
+    echo
+    help
     exit 1
 fi
 
